# Generated by Django 3.2.8 on 2022-02-18 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 2, 0, 44, 921288)),
        ),
    ]
