# Generated by Django 3.2.8 on 2022-02-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
